# Generated by Django 2.2.5 on 2021-05-14 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('OR', 'Oracle'), ('WF', 'Wolf'), ('KN', 'Knight'), ('HM', 'Human')], default='BE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100)),
                ('profession', models.CharField(choices=[('OR', 'Oracle'), ('WF', 'Wolf'), ('KN', 'Knight'), ('HM', 'Human')], default='HM', max_length=20)),
                ('alive', models.BooleanField(default=True)),
                ('win', models.CharField(choices=[('OR', 'Oracle'), ('WF', 'Wolf'), ('KN', 'Knight'), ('HM', 'Human')], default='人類たちの勝利', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
        ),
    ]
